export const LPC_ACTION_ROW_MAP: Record<string, number> = {
    "spellcast": 0,
    "thrust": 4,
    "walk": 8,
    "slash": 12,
    "shoot": 16,
    "hurt": 20,
    "climb": 21,
    "idle": 22,
    "jump": 26,
    "sit": 30,
    "emote": 34,
    "run": 38,
    "combat_idle": 42,
    "punch": 50,
    "pull": 54,
    "push": 56,
};

export const LPC_ANIMATION_FOLDERS = Object.keys(LPC_ACTION_ROW_MAP);

export const LPC_LAYER_ORDER = [
    "shadow",
    "body",
    "head",
    "eyes",
    "beard",
    "facial",
    "hair",
    "legs",
    "feet",
    "torso",
    "neck",
    "arms",
    "wrists",
    "bauldron",
    "shoulders",
    "belt",
    "backpack",
    "quiver",
    "hat",
    "cape",
    "shield",
    "weapon",
    "tools",
];
