import type { RowDesc} from "./anchorScanner";

export const SPRITE_ROWS: RowDesc[] = [
    { name: "SPELLCASTUP", row: 0, frames: 7 },
    { name: "SPELLCASTLEFT", row: 1, frames: 7 },
    { name: "SPELLCASTDOWN", row: 2, frames: 7 },
    { name: "SPELLCASTRIGHT", row: 3, frames: 7 },
    { name: "THRUSTUP", row: 4, frames: 8 },
    { name: "THRUSTLEFT", row: 5, frames: 8 },
    { name: "THRUSTDOWN", row: 6, frames: 8 },
    { name: "THRUSTRIGHT", row: 7, frames: 8 },
    { name: "MOVEUP", row: 8, frames: 9 },
    { name: "MOVELEFT", row: 9, frames: 9 },
    { name: "MOVEDOWN", row: 10, frames: 9 },
    { name: "MOVERIGHT", row: 11, frames: 9 },
    { name: "SLASHUP", row: 12, frames: 6 },
    { name: "SLASHLEFT", row: 13, frames: 6 },
    { name: "SLASHDOWN", row: 14, frames: 6 },
    { name: "SLASHRIGHT", row: 15, frames: 6 },
    { name: "SHOOTUP", row: 16, frames: 10 },
    { name: "SHOOTLEFT", row: 17, frames: 10 },
    { name: "SHOOTDOWN", row: 18, frames: 10 },
    { name: "SHOOTRIGHT", row: 19, frames: 10 },
    { name: "HURT", row: 20, frames: 6 },
    { name: "CLIMBUP", row: 21, frames: 6 },
    { name: "IDLEUP", row: 22, frames: 2 },
    { name: "IDLELEFT", row: 23, frames: 2 },
    { name: "IDLEDOWN", row: 24, frames: 2 },
    { name: "IDLERIGHT", row: 25, frames: 2 },
    { name: "JUMPUP", row: 26, frames: 5 },
    { name: "JUMPLEFT", row: 27, frames: 5 },
    { name: "JUMPDOWN", row: 28, frames: 5 },
    { name: "JUMPRIGHT", row: 29, frames: 5 },
    { name: "SITUP", row: 30, frames: 3 },
    { name: "SITLEFT", row: 31, frames: 3 },
    { name: "SITDOWN", row: 32, frames: 3 },
    { name: "SITRIGHT", row: 33, frames: 3 },
    { name: "EMOTE1UP", row: 34, frames: 3 },
    { name: "EMOTE1LEFT", row: 35, frames: 3 },
    { name: "EMOTE1DOWN", row: 36, frames: 3 },
    { name: "EMOTE1RIGHT", row: 37, frames: 3 },
    { name: "RUNUP", row: 38, frames: 8 },
    { name: "RUNLEFT", row: 39, frames: 8 },
    { name: "RUNDOWN", row: 40, frames: 8 },
    { name: "RUNRIGHT", row: 41, frames: 8 },
    { name: "COMBATIDLEUP", row: 42, frames: 2 },
    { name: "COMBATIDLELEFT", row: 43, frames: 2 },
    { name: "COMBATIDLEDOWN", row: 44, frames: 2 },
    { name: "COMBATIDLERIGHT", row: 45, frames: 2 },
    { name: "PUNCHUP", row: 50, frames: 6 },
    { name: "PUNCHLEFT", row: 51, frames: 6 },
    { name: "PUNCHDOWN", row: 52, frames: 6 },
    { name: "PUNCHRIGHT", row: 53, frames: 6 },
    { name: "PULLLEFT", row: 54, frames: 9 },
    { name: "PULLRIGHT", row: 55, frames: 9 },
    { name: "PUSHLEFT", row: 56, frames: 9 },
    { name: "PUSHRIGHT", row: 57, frames: 9 },
    { name: "DANCE", row: 2, frames: 7 },
];

export const SPRITE_ROW_MAP = new Map(SPRITE_ROWS.map(r => [r.name, r]));
